// <auto-generated />
using System;
using App.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace App.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20201027125315_SeedingData")]
    partial class SeedingData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("App.Entities.Award", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Awards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Microsoft Most Valuable Professional",
                            Title = "MVP"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Microsoft Certified Application Developer",
                            Title = "MCAD"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Microsoft Certified Solution Developer",
                            Title = "MCSD"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Microsoft Certified Systems Engineer",
                            Title = "MCSE"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Microsoft Certified Database Administrator",
                            Title = "MCDBA"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Microsoft Certified IT Professional",
                            Title = "MCITP"
                        });
                });

            modelBuilder.Entity("App.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(1958, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Bill",
                            LastName = "Gates"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(1960, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Severus",
                            LastName = "Snape"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(1965, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Arthur",
                            LastName = "Weasley"
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(1980, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Draco",
                            LastName = "Malfoy"
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateTime(1980, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ginny",
                            LastName = "Weasley"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
